[build]
  base = "webapp_frontend"
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_BASE_URL = "https://your-backend-url.railway.app"