name: 🚀 Deploy Nepal Office Tracker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        working-directory: webapp_frontend
        run: npm install
        
      - name: Build React app
        working-directory: webapp_frontend
        env:
          REACT_APP_API_BASE_URL: https://nepal-office-tracker-production.up.railway.app
        run: npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./webapp_frontend/build
          cname: nepal-office-tracker.pages.dev